name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace environment variables in JavaScript
        run: |
          sed -i 's|%DB_URL%|${{ secrets.DB_URL }}|g' scripts/functions.js

      - name: Deploy
        run: ./deploy.sh
